### ISSUE TITLE
Profile Photos

### ISSUE THREAD

**Issue by GitLukeW** [TeamProductionSystem/Team_Production_System_BE#17]
**Describe the bug**
The current code runs fine, but we are not seeing the photo upload when submitting the patch request. 

**To Reproduce**
1. Create a user with a POST to http://127.0.0.1:8000/auth/users/
2. Create a token with a POST to http://127.0.0.1:8000/auth/token/login/
3. Submit a patch request with the profile photo to http://127.0.0.1:8000/myprofile/
4. Currently the "profile_photo" field will be null. 

**Expected behavior**
The "profile_photo" field should populate with the submitted photo. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser: Chrome
 - Tools: Insomnia
 

**Additional context**
N/A

**Comment by jeromecox** [comment]
I believe I have fixed this via PR #50

**Comment by GitLukeW** [comment]
Thanks @jeromecox!!
