### ISSUE TITLE
Nest the Availability Serializer with the Mentor List

### ISSUE THREAD

**Issue by GitLukeW** [TeamProductionSystem/Team_Production_System_BE#49]
**Describe the bug**
The frontend would like the mentor list to have the availability nested into that endpoint. 

**Expected behavior**
Currently the mentor list endpoint is:

```
	{
		"pk": 6,
		"username": "Ben",
		"first_name": "",
		"last_name": "",
		"is_mentor": true,
		"mentor_profile": {
			"pk": 6,
			"about_me": "Hi, I'm Ben!!!!",
			"skills": "HTML"
		}
	},
```

And the availability is:
```
	{
		"pk": 21,
		"mentor": 4,
		"start_time": "2023-03-23T14:30:00Z",
		"end_time": "2023-03-23T15:30:00Z"
	},
	
```

The frontend would like these nested all in one. 

**Additional context**
The mentors list is using the mentors_profile serializer and the availabilities is using the availability serializer.

**Comment by jeromecox** [comment]
I believe this is solved with PR #51

**Comment by GitLukeW** [comment]
Currently https://github.com/TeamProductionSystem/Team_Production_System_BE/pull/51 is throwing a 500 error on the production server, but not on our locals. The production server has been rolled back until we can figure out the issue.

**Comment by GitLukeW** [comment]
No dice on 53. Still getting a 500 error.

**Comment by GitLukeW** [comment]
Fixed with PR54.
